// Generated by wake — semantic UI compiler
// Source: fleet.observatory
// This file is a build artifact. Edit the .wake source, not this file.

(function() {
'use strict';

// ── Value equality (Clojure = semantics) ─────────────
function equiv(a, b) {
  // nil: both null and undefined represent Clojure nil.
  if (a == null || b == null) return a == null && b == null;
  // identical refs are trivially equal.
  if (a === b) return true;
  const ta = typeof a, tb = typeof b;
  // scalars: numbers, strings (keywords emit as bare strings), booleans.
  if (ta !== "object" || tb !== "object") return a === b;
  // both are objects (arrays, plain objects/records, Sets, ...).
  const aArr = Array.isArray(a), bArr = Array.isArray(b);
  if (aArr || bArr) {
    if (!aArr || !bArr) return false;
    if (a.length !== b.length) return false;
    for (let i = 0; i < a.length; i++) if (!equiv(a[i], b[i])) return false;
    return true;
  }
  const aSet = a instanceof Set, bSet = b instanceof Set;
  if (aSet || bSet) {
    if (!aSet || !bSet) return false;
    if (a.size !== b.size) return false;
    const bItems = [...b];
    const used = new Array(bItems.length).fill(false);
    outer: for (const x of a) {
      for (let i = 0; i < bItems.length; i++) {
        if (!used[i] && equiv(x, bItems[i])) { used[i] = true; continue outer; }
      }
      return false;
    }
    return true;
  }
  // plain objects: maps AND records — same own keys, recursive equiv.
  const ak = Object.keys(a), bk = Object.keys(b);
  if (ak.length !== bk.length) return false;
  for (const k of ak) {
    if (!Object.prototype.hasOwnProperty.call(b, k)) return false;
    if (!equiv(a[k], b[k])) return false;
  }
  return true;
}
function mix(h, c) {
  return ((h << 5) - h + c) | 0;
}
function hash(x) {
  if (x == null) return 0;
  const t = typeof x;
  if (t === "number") {
    return mix(1, x | 0) ^ ((x * 2654435761) | 0);
  }
  if (t === "string") {
    let h = 2;
    for (let i = 0; i < x.length; i++) h = mix(h, x.charCodeAt(i));
    return h | 0;
  }
  if (t === "boolean") return x ? 3 : 4;
  if (Array.isArray(x)) {
    let h = 5;
    for (let i = 0; i < x.length; i++) h = mix(h, hash(x[i]));
    return h | 0;
  }
  if (x instanceof Set) {
    let acc = 0;
    for (const e of x) acc = (acc + hash(e)) | 0;
    return mix(6, acc);
  }
  if (t === "object") {
    let acc = 0;
    for (const k of Object.keys(x)) {
      acc = (acc + mix(hash(k), hash(x[k]))) | 0;
    }
    return mix(7, acc);
  }
  return mix(8, hash(String(x)));
}

// ── Store ──────────────────────────────────────────
const agents = (() => {
  let nextEid = 1;
  const entities = new Map();
  const watchers = [];
  function notify(evt) { for (const fn of watchers) fn(evt); }
  return {
    add(fields) {
      const eid = nextEid++;
      const entity = { ...fields, eid };
      entities.set(eid, entity);
      notify({ type: 'add', eid, entity });
      return entity;
    },
    get(eid) { return entities.get(eid); },
    update(eid, attr, value) {
      const entity = entities.get(eid);
      if (!entity) return false;
      const old = entity[attr];
      if (equiv(old, value)) return false;
      entity[attr] = value;
      notify({ type: 'update', eid, entity, attr, old, 'new': value });
      return true;
    },
    all() { return Array.from(entities.values()); },
    remove(eid) {
      const entity = entities.get(eid);
      if (!entity) return;
      entities.delete(eid);
      notify({ type: 'remove', eid, entity });
    },
    addBack(entity) {
      entities.set(entity.eid, entity);
      if (entity.eid >= nextEid) nextEid = entity.eid + 1;
      notify({ type: 'add', eid: entity.eid, entity });
    },
    watch(fn) { watchers.push(fn); },
    load(items) {
      entities.clear();
      let maxEid = 0;
      for (const item of items) { entities.set(item.eid, item); if (item.eid > maxEid) maxEid = item.eid; }
      nextEid = maxEid + 1;
      notify({ type: 'load' });
    },
    snapshot() { return Array.from(entities.values()); }
  };
})();

// ── Component ────────────────────────────────────────
function agent_row_create(props) {
  const el_0 = document.createElement("div");
  el_0.className = "px-4 py-3 border-b border-border";
  const el_1 = document.createElement("div");
  el_1.className = "flex items-center justify-between";
  const el_2 = document.createElement("span");
  el_2.textContent = props.uuid || '';
  const el_3 = document.createElement("span");
  el_3.textContent = props.online || '';
  el_1.appendChild(el_2);
  el_1.appendChild(el_3);
  const el_4 = document.createElement("div");
  el_4.textContent = props.roles || '';
  el_0.appendChild(el_1);
  el_0.appendChild(el_4);
  return {
    el: el_0,
    update: {
    uuid(v) { el_2.textContent = v; },
    online(v) { el_3.textContent = v; },
    roles(v) { el_4.textContent = v; }
    },
    nodes: {
    uuid: el_2,
    online: el_3,
    roles: el_4
    },
    destroy() { el_0.remove(); }
  };
}

// ── Detail Component ─────────────────────────────────
function agent_detail_create(props) {
  const el_0 = document.createElement("div");
  el_0.className = "p-6 flex flex-col gap-3";
  const el_1 = document.createElement("h2");
  el_1.textContent = props.uuid || '';
  const el_2 = document.createElement("div");
  el_2.textContent = props.roles || '';
  const el_3 = document.createElement("div");
  el_3.className = "flex flex-col gap-1 mt-2";
  const el_4 = document.createElement("div");
  el_4.textContent = "Model";
  const el_5 = document.createElement("div");
  el_5.textContent = props.model || '';
  const el_6 = document.createElement("div");
  el_6.textContent = "Online";
  const el_7 = document.createElement("div");
  el_7.textContent = props.online || '';
  const el_8 = document.createElement("div");
  el_8.textContent = "Thread";
  const el_9 = document.createElement("div");
  el_9.textContent = props.current_thread || '';
  const el_10 = document.createElement("div");
  el_10.textContent = "Workflow";
  const el_11 = document.createElement("div");
  el_11.textContent = props.active_workflow || '';
  const el_12 = document.createElement("div");
  el_12.textContent = "Cost (USD)";
  const el_13 = document.createElement("div");
  el_13.textContent = props.cost_usd || '';
  el_3.appendChild(el_4);
  el_3.appendChild(el_5);
  el_3.appendChild(el_6);
  el_3.appendChild(el_7);
  el_3.appendChild(el_8);
  el_3.appendChild(el_9);
  el_3.appendChild(el_10);
  el_3.appendChild(el_11);
  el_3.appendChild(el_12);
  el_3.appendChild(el_13);
  el_0.appendChild(el_1);
  el_0.appendChild(el_2);
  el_0.appendChild(el_3);
  return {
    el: el_0,
    update: {
    uuid(v) { el_1.textContent = v; },
    roles(v) { el_2.textContent = v; },
    model(v) { el_5.textContent = v; },
    online(v) { el_7.textContent = v; },
    current_thread(v) { el_9.textContent = v; },
    active_workflow(v) { el_11.textContent = v; },
    cost_usd(v) { el_13.textContent = v; }
    },
    nodes: {
    uuid: el_1,
    roles: el_2,
    model: el_5,
    online: el_7,
    current_thread: el_9,
    active_workflow: el_11,
    cost_usd: el_13
    },
    destroy() { el_0.remove(); }
  };
}

// ── Undo / Redo ─────────────────────────────────────
const undoStack = [];
const redoStack = [];
let undoing = false;
let txBuffer = null;

function recordUndo(entry) {
  if (undoing) return;
  if (txBuffer) { txBuffer.push(entry); return; }
  undoStack.push(entry);
  redoStack.length = 0;
}

function beginTransaction() { txBuffer = []; }
function commitTransaction() {
  if (txBuffer && txBuffer.length > 0) {
    undoStack.push({ type: 'batch', ops: txBuffer });
    redoStack.length = 0;
  }
  txBuffer = null;
}

function applyUndo(op) {
  if (op.type === 'update') op.store.update(op.eid, op.attr, op.old);
  if (op.type === 'add') op.store.remove(op.eid);
  if (op.type === 'remove') op.store.addBack(op.entity);
}
function applyRedo(op) {
  if (op.type === 'update') op.store.update(op.eid, op.attr, op['new']);
  if (op.type === 'add') op.store.addBack(op.entity);
  if (op.type === 'remove') op.store.remove(op.eid);
}

function undo() {
  const entry = undoStack.pop();
  if (!entry) return;
  redoStack.push(entry);
  undoing = true;
  if (entry.type === 'batch') {
    for (let i = entry.ops.length - 1; i >= 0; i--) applyUndo(entry.ops[i]);
  } else {
    applyUndo(entry);
  }
  undoing = false;
}

function redo() {
  const entry = redoStack.pop();
  if (!entry) return;
  undoStack.push(entry);
  undoing = true;
  if (entry.type === 'batch') {
    for (const op of entry.ops) applyRedo(op);
  } else {
    applyRedo(entry);
  }
  undoing = false;
}

// ── Live external feed ───────────────────────────────
const _feedUrl = "http://localhost:8088/presence";
const _feedStore = agents;
const _feedStoreName = "agents";
const _feedIdField = "uuid";
const _feedIndex = new Map(); // identity value -> stable eid
let _feedTimer = null;
let _feedWS = null;
let _feedPending = null;

// Diff incoming rows into the store by identity field; per-row update/add/remove (change-gated).
// Returns the identity values (uuids) that actually moved — handed to feed.onUpdate subscribers.
function applyFeedRows(rows) {
  const arr = Array.isArray(rows) ? rows : [];
  if (!_feedIdField) {
    // No identity field declared: fall back to whole-store replace.
    _feedStore.load(arr.map((row, i) => ({ ...row, eid: i + 1 })));
    return;
  }
  const seen = new Set();
  const changed = [];
  for (const row of arr) {
    const key = String(row[_feedIdField]);
    seen.add(key);
    let eid = _feedIndex.get(key);
    if (eid == null) {
      const ent = _feedStore.add({ ...row });
      _feedIndex.set(key, ent.eid);
      changed.push(key);                                   // new agent
    } else {
      let moved = false;
      for (const k in row) { if (k !== 'eid' && _feedStore.update(eid, k, row[k])) moved = true; }
      if (moved) changed.push(key);                        // some field actually moved (not gated away)
    }
  }
  for (const [key, eid] of Array.from(_feedIndex.entries())) {
    if (!seen.has(key)) { _feedStore.remove(eid); _feedIndex.delete(key); changed.push(key); }  // vanished
  }
  if (changed.length) _emitFeedUpdate(changed);
}

async function loadFromFeed() {
  try {
    const r = await fetch(_feedUrl);
    if (!r.ok) return;
    applyFeedRows(await r.json());
  } catch (err) { console.error('feed load failed:', err); }
}

// Derive the /live WS url from the feed http url: same host, ws(s) scheme, sibling /live path.
function feedWsUrl() {
  try {
    const u = new URL(_feedUrl, location.href);
    u.protocol = (u.protocol === 'https:') ? 'wss:' : 'ws:';
    const p = u.pathname;
    const slash = p.lastIndexOf('/');
    u.pathname = (slash >= 0 ? p.slice(0, slash) : '') + '/live';
    return u.toString();
  } catch (_) { return null; }
}

function openFeedWS() {
  const wsUrl = feedWsUrl();
  if (!wsUrl) return;
  try {
    const ws = new WebSocket(wsUrl);
    _feedWS = ws;
    ws.onmessage = () => {
      if (_feedPending) return; // coalesce a burst of commits into one refetch
      _feedPending = setTimeout(() => { _feedPending = null; loadFromFeed(); }, 150);
    };
    ws.onclose = () => { _feedWS = null; setTimeout(openFeedWS, 2000); };
    ws.onerror = () => { try { ws.close(); } catch (_) {} };
  } catch (_) { setTimeout(openFeedWS, 2000); }
}

function startFeed() {
  loadFromFeed();                                  // initial snapshot
  openFeedWS();                                    // real-time push
  _feedTimer = setInterval(loadFromFeed, 15000);   // slow backstop for any dropped commit
}

// --- window.wake: the cross-surface bus (SEAM with the shell). The shell owns the outer
// layout and reads our stores/selection/feed by contract. Selection speaks IDENTITY (uuid);
// we map uuid->eid at our boundary so neither side leaks its internal id. ---
const _feedSubs = new Set();
let _selectedUuid = null;

function _emitFeedUpdate(changed) {
  const payload = { name: _feedStoreName, changed };     // { name, changed:[uuid,...] } — the delta we already diffed
  for (const cb of _feedSubs) { try { cb(payload); } catch (err) { console.error('wake feed subscriber threw:', err); } }
}

(function installWakeBus() {
  const wake = (window.wake = window.wake || {});
  wake.stores = wake.stores || {};
  wake.stores[_feedStoreName] = _feedStore;
  wake.selection = wake.selection || {
    // uuid -> eid at our boundary. No-op (false) if the agent isn't indexed yet; never throws.
    set(uuid) {
      if (uuid == null) { _selectedUuid = null; return false; }
      const key = String(uuid);
      if (!_feedIndex.has(key)) return false;
      _selectedUuid = key;
      return true;
    },
    get() { return _selectedUuid; },                       // null cleanly when nothing is selected
  };
  wake.feed = wake.feed || {};
  wake.feed.name = _feedStoreName;
  wake.feed.onUpdate = (cb) => { if (typeof cb === 'function') _feedSubs.add(cb); return () => _feedSubs.delete(cb); };
  // Ready signal: resolve a promise AND fire an event — a subscriber loading before OR after
  // us both win, with no guarding for undefined.
  window.wakeReady = Promise.resolve(wake);
  try { window.dispatchEvent(new CustomEvent('wake:ready', { detail: wake })); } catch (_) {}
})();

// ── Init ─────────────────────────────────────────────

          function init() {
            const root = document.getElementById(window.WAKE_MOUNT_ID || 'app');
            const container = document.createElement('div');
            container.className = 'flex flex-col h-screen';

            const formEl = document.createElement('form');
            formEl.className = 'flex flex-col gap-3 p-4';
          
  const form_uuid_label = document.createElement('label');
  form_uuid_label.className = 'text-xs font-medium uppercase text-muted-foreground';
  form_uuid_label.textContent = "Uuid";
  formEl.appendChild(form_uuid_label);
  const form_uuid = document.createElement('input');
  form_uuid.className = 'px-3 py-2 border border-input rounded-md bg-background text-foreground text-sm';
  form_uuid.placeholder = "Uuid";
  formEl.appendChild(form_uuid);

            const submitBtn = document.createElement('button');
            submitBtn.type = 'submit';
            submitBtn.className = 'px-4 py-2 bg-primary text-primary-foreground rounded-md text-sm font-medium hover:opacity-90';
            submitBtn.textContent = 'Add';
            formEl.appendChild(submitBtn);
          
  formEl.addEventListener('submit', (e) => {
    e.preventDefault();
    const first = form_uuid.value.trim();
    if (!first) return;
    agents.add({ uuid: form_uuid.value.trim() });
    form_uuid.value = '';
  });
  container.appendChild(formEl);


            const headerEl = document.createElement('div');
            headerEl.className = 'p-4 border-b border-border';
            const titleEl = document.createElement('h1');
            titleEl.className = 'text-lg font-semibold text-foreground';
          
  titleEl.textContent = "Fleet Observatory";
  headerEl.appendChild(titleEl);

            const statsEl = document.createElement('div');
            statsEl.className = 'mt-2 text-xs text-muted-foreground';
            headerEl.appendChild(statsEl);
            const listEl = document.createElement('div');
            listEl.className = 'flex-1 overflow-y-auto';
            const splitPane = document.createElement('div');
            splitPane.className = 'flex flex-1 min-h-0';
            const leftPane = document.createElement('div');
            leftPane.className = 'flex flex-col w-1/2 min-h-0 border-r border-border';
            leftPane.appendChild(headerEl);
            leftPane.appendChild(listEl);
            splitPane.appendChild(leftPane);
            const rightPane = document.createElement('div');
            rightPane.className = 'w-1/2 min-h-0 overflow-y-auto';
            const detailEmpty = document.createElement('div');
            detailEmpty.className = 'flex items-center justify-center h-full text-muted-foreground text-sm';
            detailEmpty.textContent = 'Select an item to view details';
            rightPane.appendChild(detailEmpty);
            splitPane.appendChild(rightPane);
            container.appendChild(splitPane);
            root.appendChild(container);
            let selectedEid = null;
            let detailInst = null;
            function selectItem(eid) {
              selectedEid = eid;
              if (detailInst) { detailInst.destroy(); detailInst = null; }
              if (eid === null) { detailEmpty.style.display = ''; return; }
              detailEmpty.style.display = 'none';
          
      const entity = agents.get(eid);
      if (!entity) return;
      detailInst = agent_detail_create(entity);

              rightPane.appendChild(detailInst.el);
            }
            const instances = new Map();
          


  // ── Escape-hatch panels (shell-owned custom panes; share window.wake) ──────
  const _wakeResolve = (path) => path.split('.').reduce((o, k) => (o == null ? null : o[k]), window);
  const panel_agent_graph = document.createElement('div');
  panel_agent_graph.id = "panel-agent-graph";
  panel_agent_graph.className = 'wake-panel';
  container.appendChild(panel_agent_graph);
  { const _fn = "framescope.mountGraph" ? _wakeResolve("framescope.mountGraph") : null;
    if (typeof _fn === 'function') { try { _fn({ el: panel_agent_graph, wake: window.wake || null }); } catch (err) { console.error('wake: panel mount threw:', err); } }
    else if ("framescope.mountGraph") console.warn('wake: panel mount fn not found:', "framescope.mountGraph"); }
  const panel_agent_stream = document.createElement('div');
  panel_agent_stream.id = "panel-agent-stream";
  panel_agent_stream.className = 'wake-panel';
  container.appendChild(panel_agent_stream);
  { const _fn = "framescope.mountStream" ? _wakeResolve("framescope.mountStream") : null;
    if (typeof _fn === 'function') { try { _fn({ el: panel_agent_stream, wake: window.wake || null }); } catch (err) { console.error('wake: panel mount threw:', err); } }
    else if ("framescope.mountStream") console.warn('wake: panel mount fn not found:', "framescope.mountStream"); }
  agents.watch((evt) => {
    if (evt.type === 'add') {
      const inst = agent_row_create(evt.entity);
      inst.el.className = (inst.el.className || '') + ' cursor-pointer hover:bg-muted/50';
      listEl.appendChild(inst.el);
      instances.set(evt.eid, inst);
      inst.el.addEventListener('click', () => selectItem(evt.eid));
      statsEl.textContent = 'Total: ' + instances.size;
      recordUndo({ type: 'add', store: agents, eid: evt.eid, entity: evt.entity });
    }

              if (evt.type === 'update') {
                const inst = instances.get(evt.eid);
                if (inst && inst.update[evt.attr]) inst.update[evt.attr](evt.new || '');
          
      if (selectedEid === evt.eid && detailInst && detailInst.update[evt.attr]) detailInst.update[evt.attr](evt.new || '');
      recordUndo({ type: 'update', store: agents, eid: evt.eid, attr: evt.attr, old: evt.old, 'new': evt.new });
    }
    if (evt.type === 'remove') {
      const inst = instances.get(evt.eid);
      if (inst) { inst.destroy(); instances.delete(evt.eid); }
      statsEl.textContent = 'Total: ' + instances.size;
      if (selectedEid === evt.eid) selectItem(null);
      recordUndo({ type: 'remove', store: agents, eid: evt.eid, entity: evt.entity });
    }
    if (evt.type === 'load') {
      listEl.innerHTML = '';
      instances.clear();
      if (selectedEid) selectItem(null);
      for (const entity of agents.all()) {
        const inst = agent_row_create(entity);
        inst.el.className = (inst.el.className || '') + ' cursor-pointer hover:bg-muted/50';
        inst.el.addEventListener('click', () => selectItem(entity.eid));
        listEl.appendChild(inst.el);
        instances.set(entity.eid, inst);
      }
      statsEl.textContent = 'Total: ' + instances.size;
    }
  });


            document.addEventListener('keydown', (e) => {
              if ((e.ctrlKey || e.metaKey) && e.key === 'z' && !e.shiftKey) { e.preventDefault(); undo(); }
              if ((e.ctrlKey || e.metaKey) && e.key === 'z' && e.shiftKey) { e.preventDefault(); redo(); }
            });
          

  startFeed();
}

init();
})();
