function typeDescriptor(type) {
  switch (type) {
    case "Int":
    case "Integer": return { kind: "integer" };
    case "Float":
    case "Double":
    case "Number": return { kind: "number" };
    case "Bool":
    case "Boolean": return { kind: "boolean" };
    case "Instant": return { kind: "instant" };
    case "Keyword": return { kind: "keyword" };
    default: return { kind: "string" };
  }
}

function operationDescriptors(checked) {
  const queries = Object.fromEntries((checked.queries ?? []).map(query => [query.name, {
    input: Object.fromEntries(query.params.map(parameter => [
      parameter.name,
      typeDescriptor(parameter.type),
    ])),
    result: {
      columns: Object.fromEntries(query.columns.map(column => [
        column.name,
        { cardinality: column.cardinality, ...typeDescriptor(column.type) },
      ])),
      kind: query.result_kind,
      ...(query.default_limit == null ? {} : { defaultLimit: query.default_limit }),
      ...(query.max_limit == null ? {} : { maxLimit: query.max_limit }),
    },
  }]));
  const commands = Object.fromEntries((checked.commands ?? []).map(command => [command.name, {
    input: Object.fromEntries((command.input ?? []).map(field => [field.name, field.type])),
    result: Object.fromEntries((command.result ?? []).map(field => [field.name, field.type])),
  }]));
  return { commands, queries };
}

export function generateWakeClient(checked) {
  if (checked === null || typeof checked !== "object"
      || typeof checked.semantic_fingerprint !== "string") {
    throw new TypeError("wake client generation requires a checked application fingerprint");
  }
  const fingerprint = checked.semantic_fingerprint;
  const descriptors = operationDescriptors(checked);
  return `// wake: checked-application ${fingerprint}
// Generated by Wake. Side-effect-free application contract module.
export const semanticFingerprint = ${JSON.stringify(fingerprint)};
export const operations = Object.freeze(${JSON.stringify(descriptors)});

function plainObject(value) {
  if (value === null || typeof value !== "object" || Array.isArray(value)) return false;
  const prototype = Object.getPrototypeOf(value);
  return prototype === Object.prototype || prototype === null;
}

function validateScalar(value, descriptor, label) {
  if (descriptor.kind === "string" || descriptor.kind === "keyword") {
    if (typeof value !== "string") throw new TypeError(label + " must be a string");
  } else if (descriptor.kind === "integer") {
    if (!Number.isSafeInteger(value) && !(typeof value === "string" && /^(?:0|-?[1-9][0-9]*)$/.test(value))) {
      throw new TypeError(label + " must be an exact integer");
    }
  } else if (descriptor.kind === "number") {
    if (typeof value !== "number" || !Number.isFinite(value)) throw new TypeError(label + " must be finite");
  } else if (descriptor.kind === "boolean") {
    if (typeof value !== "boolean") throw new TypeError(label + " must be boolean");
  } else if (descriptor.kind === "instant") {
    if (!plainObject(value) || typeof value.epochSeconds !== "string" || typeof value.nanos !== "string") {
      throw new TypeError(label + " must be an exact instant");
    }
  }
  return value;
}

function validateRecord(value, fields, label) {
  if (!plainObject(value)) throw new TypeError(label + " must be an object");
  const expected = Object.keys(fields);
  for (const name of expected) {
    if (!Object.hasOwn(value, name)) throw new TypeError(label + " requires " + name);
    validateScalar(value[name], fields[name], label + "." + name);
  }
  for (const name of Object.keys(value)) {
    if (!Object.hasOwn(fields, name)) throw new TypeError(label + " rejects " + name);
  }
  return value;
}

export function queryDescriptor(name) {
  const descriptor = operations.queries[name];
  if (!descriptor) throw new TypeError("unknown checked query " + name);
  return descriptor;
}

export function commandDescriptor(name) {
  const descriptor = operations.commands[name];
  if (!descriptor) throw new TypeError("unknown checked command " + name);
  return descriptor;
}

export function validateQueryInput(name, value) {
  return validateRecord(value, queryDescriptor(name).input, "query " + name + " input");
}
`;
}
