// Generated by wake — semantic UI compiler
// Source: wake.app
// This file is a build artifact. Edit the .wake source, not this file.

(function() {
'use strict';

// ── Value equality (Clojure = semantics) ─────────────
function equiv(a, b) {
  // nil: both null and undefined represent Clojure nil.
  if (a == null || b == null) return a == null && b == null;
  // identical refs are trivially equal.
  if (a === b) return true;
  const ta = typeof a, tb = typeof b;
  // scalars: numbers, strings (keywords emit as bare strings), booleans.
  if (ta !== "object" || tb !== "object") return a === b;
  // both are objects (arrays, plain objects/records, Sets, ...).
  const aArr = Array.isArray(a), bArr = Array.isArray(b);
  if (aArr || bArr) {
    if (!aArr || !bArr) return false;
    if (a.length !== b.length) return false;
    for (let i = 0; i < a.length; i++) if (!equiv(a[i], b[i])) return false;
    return true;
  }
  const aSet = a instanceof Set, bSet = b instanceof Set;
  if (aSet || bSet) {
    if (!aSet || !bSet) return false;
    if (a.size !== b.size) return false;
    const bItems = [...b];
    const used = new Array(bItems.length).fill(false);
    outer: for (const x of a) {
      for (let i = 0; i < bItems.length; i++) {
        if (!used[i] && equiv(x, bItems[i])) { used[i] = true; continue outer; }
      }
      return false;
    }
    return true;
  }
  // plain objects: maps AND records — same own keys, recursive equiv.
  const ak = Object.keys(a), bk = Object.keys(b);
  if (ak.length !== bk.length) return false;
  for (const k of ak) {
    if (!Object.prototype.hasOwnProperty.call(b, k)) return false;
    if (!equiv(a[k], b[k])) return false;
  }
  return true;
}
function mix(h, c) {
  return ((h << 5) - h + c) | 0;
}
function hash(x) {
  if (x == null) return 0;
  const t = typeof x;
  if (t === "number") {
    return mix(1, x | 0) ^ ((x * 2654435761) | 0);
  }
  if (t === "string") {
    let h = 2;
    for (let i = 0; i < x.length; i++) h = mix(h, x.charCodeAt(i));
    return h | 0;
  }
  if (t === "boolean") return x ? 3 : 4;
  if (Array.isArray(x)) {
    let h = 5;
    for (let i = 0; i < x.length; i++) h = mix(h, hash(x[i]));
    return h | 0;
  }
  if (x instanceof Set) {
    let acc = 0;
    for (const e of x) acc = (acc + hash(e)) | 0;
    return mix(6, acc);
  }
  if (t === "object") {
    let acc = 0;
    for (const k of Object.keys(x)) {
      acc = (acc + mix(hash(k), hash(x[k]))) | 0;
    }
    return mix(7, acc);
  }
  return mix(8, hash(String(x)));
}

// ── Stores ─────────────────────────────────────────
const contacts = (() => {
  let nextEid = 1;
  const entities = new Map();
  const watchers = [];
  function notify(evt) { for (const fn of watchers) fn(evt); }
  return {
    add(fields) {
      const eid = nextEid++;
      const entity = { ...fields, eid };
      entities.set(eid, entity);
      notify({ type: 'add', eid, entity });
      return entity;
    },
    get(eid) { return entities.get(eid); },
    update(eid, attr, value) {
      const entity = entities.get(eid);
      if (!entity) return;
      const old = entity[attr];
      if (equiv(old, value)) return;
      entity[attr] = value;
      notify({ type: 'update', eid, entity, attr, old, 'new': value });
    },
    all() { return Array.from(entities.values()); },
    remove(eid) {
      const entity = entities.get(eid);
      if (!entity) return;
      entities.delete(eid);
      notify({ type: 'remove', eid, entity });
    },
    addBack(entity) {
      entities.set(entity.eid, entity);
      if (entity.eid >= nextEid) nextEid = entity.eid + 1;
      notify({ type: 'add', eid: entity.eid, entity });
    },
    watch(fn) { watchers.push(fn); },
    load(items) {
      entities.clear();
      let maxEid = 0;
      for (const item of items) { entities.set(item.eid, item); if (item.eid > maxEid) maxEid = item.eid; }
      nextEid = maxEid + 1;
      notify({ type: 'load' });
    },
    snapshot() { return Array.from(entities.values()); }
  };
})();

const notes = (() => {
  let nextEid = 1;
  const entities = new Map();
  const watchers = [];
  function notify(evt) { for (const fn of watchers) fn(evt); }
  return {
    add(fields) {
      const eid = nextEid++;
      const entity = { ...fields, eid };
      entities.set(eid, entity);
      notify({ type: 'add', eid, entity });
      return entity;
    },
    get(eid) { return entities.get(eid); },
    update(eid, attr, value) {
      const entity = entities.get(eid);
      if (!entity) return;
      const old = entity[attr];
      if (equiv(old, value)) return;
      entity[attr] = value;
      notify({ type: 'update', eid, entity, attr, old, 'new': value });
    },
    all() { return Array.from(entities.values()); },
    remove(eid) {
      const entity = entities.get(eid);
      if (!entity) return;
      entities.delete(eid);
      notify({ type: 'remove', eid, entity });
    },
    addBack(entity) {
      entities.set(entity.eid, entity);
      if (entity.eid >= nextEid) nextEid = entity.eid + 1;
      notify({ type: 'add', eid: entity.eid, entity });
    },
    byContact(fkEid) { return Array.from(entities.values()).filter(e => e.contact === fkEid); },
    watch(fn) { watchers.push(fn); },
    load(items) {
      entities.clear();
      let maxEid = 0;
      for (const item of items) { entities.set(item.eid, item); if (item.eid > maxEid) maxEid = item.eid; }
      nextEid = maxEid + 1;
      notify({ type: 'load' });
    },
    snapshot() { return Array.from(entities.values()); }
  };
})();
// ── DOM refs ──────────────────────────────────────
let form_add_contact;
let form_add_contact_name;
let form_add_contact_email;
let form_add_contact_company;
let form_add_contact_status;
let ld_contact_search;
let ld_contact_stats;
let ld_contact_list;
let ld_contact_detail;

// ── Detail panel ────────────────────────────────────
let selectedContact = null;
let activeTab = 'overview';

function selectContact(eid) {
  selectedContact = eid;
  renderDetail();
}

const detailNodes = {};

const fieldTypes = { "status": { kind: "select", options: ["active", "inactive", "archived"] } };

function makeEditable(el, attr) {
  el.style.cursor = 'pointer';
  el.addEventListener('click', () => {
    if (!selectedContact) return;
    let done = false;
    const ft = fieldTypes[attr];
    const kind = ft ? ft.kind : 'text';
    let input;
    if (kind === 'select') {
      input = document.createElement('select');
      for (const opt of ft.options) {
        const o = document.createElement('option');
        o.value = opt; o.textContent = opt;
        if (opt === el.textContent) o.selected = true;
        input.appendChild(o);
      }
    } else if (kind === 'checkbox') {
      input = document.createElement('input');
      input.type = 'checkbox';
      input.checked = el.textContent === 'true';
    } else {
      input = document.createElement('input');
      input.type = kind;
      input.value = el.textContent;
    }
    input.className = 'text-sm w-full px-1 py-0 border border-input rounded bg-background text-foreground outline-none';
    el.replaceWith(input);
    input.focus();
    function commit() {
      if (done) return;
      done = true;
      const val = kind === 'checkbox' ? String(input.checked) : input.value.trim();
      input.replaceWith(el);
      contacts.update(selectedContact, attr, val);
    }
    if (kind === 'select') {
      input.addEventListener('change', commit);
      input.addEventListener('blur', commit);
    } else {
      input.addEventListener('blur', commit);
      input.addEventListener('keydown', (e) => {
        if (e.key === 'Enter') { e.preventDefault(); commit(); }
        if (e.key === 'Escape') { done = true; input.replaceWith(el); }
      });
    }
  });
}

function buildDetailPanel() {
  const container = ld_contact_detail;

  detailNodes.emptyState = document.createElement('div');
  detailNodes.emptyState.className = 'flex items-center justify-center h-full text-muted-foreground text-sm';
  detailNodes.emptyState.textContent = 'Select a contact to view details';

  detailNodes.wrapper = document.createElement('div');
  detailNodes.wrapper.className = 'flex flex-col h-full';
  detailNodes.wrapper.style.display = 'none';

  const header = document.createElement('div');
  header.className = 'flex items-center justify-between p-4 border-b border-border';
  const headerLeft = document.createElement('div');
  detailNodes.title = document.createElement('h2');
  detailNodes.title.className = 'text-lg font-semibold';
  detailNodes.subtitle = document.createElement('p');
  detailNodes.subtitle.className = 'text-sm text-muted-foreground';
  headerLeft.appendChild(detailNodes.title);
  headerLeft.appendChild(detailNodes.subtitle);
  const headerRight = document.createElement('div');
  headerRight.className = 'flex items-center gap-1';
  const deleteBtn = document.createElement('button');
  deleteBtn.className = 'p-1 rounded hover:bg-red-100 text-muted-foreground hover:text-red-600 transition-colors';
  deleteBtn.innerHTML = '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M3 6h18"></path><path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6"></path><path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2"></path></svg>';
  deleteBtn.addEventListener('click', () => {
    if (!selectedContact) return;
    beginTransaction();
    for (const r of notes.byContact(selectedContact)) notes.remove(r.eid);
    contacts.remove(selectedContact);
    commitTransaction();
  });
  const closeBtn = document.createElement('button');
  closeBtn.className = 'p-1 rounded hover:bg-muted';
  closeBtn.innerHTML = '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg>';
  closeBtn.addEventListener('click', () => selectContact(null));
  headerRight.appendChild(deleteBtn);
  headerRight.appendChild(closeBtn);
  header.appendChild(headerLeft);
  header.appendChild(headerRight);
  detailNodes.wrapper.appendChild(header);

  const tabBar = document.createElement('div');
  tabBar.className = 'flex border-b border-border';
  detailNodes.tabOverview = document.createElement('button');
  detailNodes.tabOverview.textContent = 'Overview';
  detailNodes.tabOverview.className = 'px-4 py-2 text-sm font-medium border-b-2 border-primary text-foreground';
  detailNodes.tabOverview.addEventListener('click', () => { activeTab = 'overview'; renderDetail(); });
  tabBar.appendChild(detailNodes.tabOverview);
  detailNodes.tab_notes = document.createElement('button');
  detailNodes.tab_notes.textContent = "Notes";
  detailNodes.tab_notes.className = 'px-4 py-2 text-sm font-medium text-muted-foreground';
  detailNodes.tab_notes.addEventListener('click', () => { activeTab = "notes"; renderDetail(); });
  tabBar.appendChild(detailNodes.tab_notes);
  detailNodes.wrapper.appendChild(tabBar);

  detailNodes.overviewContent = document.createElement('div');
  detailNodes.overviewContent.className = 'p-4 flex-1 overflow-y-auto';
  const grid = document.createElement('div');
  grid.className = 'grid grid-cols-2 gap-3';
  const nameLabel = document.createElement('span');
  nameLabel.className = 'text-xs font-medium uppercase text-muted-foreground';
  nameLabel.textContent = "Name";
  grid.appendChild(nameLabel);
  detailNodes.field_name = document.createElement('span');
  detailNodes.field_name.className = 'text-sm';
  grid.appendChild(detailNodes.field_name);
  makeEditable(detailNodes.field_name, "name");
  const emailLabel = document.createElement('span');
  emailLabel.className = 'text-xs font-medium uppercase text-muted-foreground';
  emailLabel.textContent = "Email";
  grid.appendChild(emailLabel);
  detailNodes.field_email = document.createElement('span');
  detailNodes.field_email.className = 'text-sm';
  grid.appendChild(detailNodes.field_email);
  makeEditable(detailNodes.field_email, "email");
  const companyLabel = document.createElement('span');
  companyLabel.className = 'text-xs font-medium uppercase text-muted-foreground';
  companyLabel.textContent = "Company";
  grid.appendChild(companyLabel);
  detailNodes.field_company = document.createElement('span');
  detailNodes.field_company.className = 'text-sm';
  grid.appendChild(detailNodes.field_company);
  makeEditable(detailNodes.field_company, "company");
  const statusLabel = document.createElement('span');
  statusLabel.className = 'text-xs font-medium uppercase text-muted-foreground';
  statusLabel.textContent = "Status";
  grid.appendChild(statusLabel);
  detailNodes.field_status = document.createElement('span');
  detailNodes.field_status.className = 'text-sm';
  grid.appendChild(detailNodes.field_status);
  makeEditable(detailNodes.field_status, "status");
  const display_nameLabel = document.createElement('span');
  display_nameLabel.className = 'text-xs font-medium uppercase text-muted-foreground';
  display_nameLabel.textContent = "Display Name";
  grid.appendChild(display_nameLabel);
  detailNodes.field_display_name = document.createElement('span');
  detailNodes.field_display_name.className = 'text-sm italic text-muted-foreground';
  grid.appendChild(detailNodes.field_display_name);
  detailNodes.overviewContent.appendChild(grid);
  detailNodes.wrapper.appendChild(detailNodes.overviewContent);

  detailNodes.notesContent = document.createElement('div');
  detailNodes.notesContent.className = 'p-4 flex-1 overflow-y-auto flex flex-col';
  detailNodes.notesContent.style.display = 'none';
  detailNodes.notesHeader = document.createElement('h3');
  detailNodes.notesHeader.className = 'text-sm font-medium mb-2';
  detailNodes.notesContent.appendChild(detailNodes.notesHeader);
  detailNodes.notesList = document.createElement('div');
  detailNodes.notesList.className = 'flex-1 space-y-2 mb-3';
  detailNodes.notesContent.appendChild(detailNodes.notesList);
  const notesFormRow = document.createElement('div');
  notesFormRow.className = 'flex gap-2';
  detailNodes.notesInput = document.createElement('textarea');
  detailNodes.notesInput.className = 'flex-1 px-3 py-2 border border-input rounded-md bg-background text-foreground text-sm resize-none';
  detailNodes.notesInput.placeholder = 'Add a note...';
  detailNodes.notesInput.rows = 2;
  notesFormRow.appendChild(detailNodes.notesInput);
  const notesAddBtn = document.createElement('button');
  notesAddBtn.className = 'px-3 py-2 bg-primary text-primary-foreground rounded-md text-sm font-medium hover:opacity-90 self-end';
  notesAddBtn.textContent = 'Add';
  notesAddBtn.addEventListener('click', () => {
  const content = detailNodes.notesInput.value.trim();
  if (!content || !selectedContact) return;
  notes.add({ content, contact: selectedContact, 'created-at': new Date().toISOString() });
  detailNodes.notesInput.value = '';
});
  notesFormRow.appendChild(notesAddBtn);
  detailNodes.notesContent.appendChild(notesFormRow);
  detailNodes.wrapper.appendChild(detailNodes.notesContent);

  container.appendChild(detailNodes.emptyState);
  container.appendChild(detailNodes.wrapper);
}

function renderNotes() {
  detailNodes.notesList.innerHTML = '';
  if (!selectedContact) return;
  detailNodes.notesHeader.textContent = 'Notes for ' + (contacts.get(selectedContact)?.name || '');
  const items = notes.byContact(selectedContact)
    .sort((a, b) => (b['created-at'] || '').localeCompare(a['created-at'] || ''));
  if (items.length === 0) {
    const empty = document.createElement('div');
    empty.className = 'text-sm text-muted-foreground';
    empty.textContent = 'No notes yet';
    detailNodes.notesList.appendChild(empty);
    return;
  }
  for (const item of items) {
    const el = document.createElement('div');
    el.className = 'p-2 border border-border rounded-md flex justify-between items-start gap-2';
    const elBody = document.createElement('div');
    elBody.className = 'flex-1 min-w-0';
    const contentEl = document.createElement('p');
    contentEl.className = 'text-sm';
    contentEl.textContent = item['content'] || '';
    elBody.appendChild(contentEl);
    const created_atEl = document.createElement('span');
    created_atEl.className = 'text-xs text-muted-foreground mt-1 block';
    created_atEl.textContent = item['created-at'] || '';
    elBody.appendChild(created_atEl);
    el.appendChild(elBody);
    const delBtn = document.createElement('button');
    delBtn.className = 'text-muted-foreground hover:text-red-600 text-sm px-1 flex-shrink-0';
    delBtn.textContent = '\u00d7';
    delBtn.addEventListener('click', () => notes.remove(item.eid));
    el.appendChild(delBtn);
    detailNodes.notesList.appendChild(el);
  }
}

function renderDetail() {
  if (!selectedContact) {
    detailNodes.emptyState.style.display = '';
    detailNodes.wrapper.style.display = 'none';
    detailNodes.title.textContent = '';
    detailNodes.subtitle.textContent = '';
    detailNodes.field_name.textContent = '';
    detailNodes.field_email.textContent = '';
    detailNodes.field_company.textContent = '';
    detailNodes.field_status.textContent = '';
    detailNodes.field_display_name.textContent = '';
    return;
  }
  const entity = contacts.get(selectedContact);
  if (!entity) {
    detailNodes.emptyState.style.display = '';
    detailNodes.wrapper.style.display = 'none';
    return;
  }
  detailNodes.emptyState.style.display = 'none';
  detailNodes.wrapper.style.display = '';

  detailNodes.title.textContent = entity.name || '';
  detailNodes.subtitle.textContent = entity.email || '';

  detailNodes.field_name.textContent = entity.name || '';
  detailNodes.field_email.textContent = entity.email || '';
  detailNodes.field_company.textContent = entity.company || '';
  detailNodes.field_status.textContent = entity.status || '';
  detailNodes.field_display_name.textContent = (entity.name || '') + " @ " + (entity.company || '');

  detailNodes.tabOverview.className = activeTab === 'overview'
    ? 'px-4 py-2 text-sm font-medium border-b-2 border-primary text-foreground'
    : 'px-4 py-2 text-sm font-medium text-muted-foreground';
  detailNodes.tab_notes.className = activeTab === "notes"
    ? 'px-4 py-2 text-sm font-medium border-b-2 border-primary text-foreground'
    : 'px-4 py-2 text-sm font-medium text-muted-foreground';

  detailNodes.overviewContent.style.display = activeTab !== 'overview' ? 'none' : '';
  detailNodes.notesContent.style.display = activeTab !== "notes" ? 'none' : '';
  if (activeTab === "notes") renderNotes();
}


// ── List view ──────────────────────────────────────
const rowEls = new Map();

function addRow(entity) {
  const row = document.createElement('div');
  row.className = 'ld-row flex items-center px-4 py-2.5 border-b border-border cursor-pointer transition-colors hover:bg-muted/50';
  const inner = document.createElement('div');
  inner.className = 'flex-1 flex gap-4';
  const nameCell = document.createElement('span');
  nameCell.className = 'text-sm truncate flex-1';
  nameCell.textContent = entity.name || '';
  inner.appendChild(nameCell);
  const emailCell = document.createElement('span');
  emailCell.className = 'text-sm truncate flex-1';
  emailCell.textContent = entity.email || '';
  inner.appendChild(emailCell);
  const companyCell = document.createElement('span');
  companyCell.className = 'text-sm truncate flex-1';
  companyCell.textContent = entity.company || '';
  inner.appendChild(companyCell);
  const statusCell = document.createElement('span');
  statusCell.className = 'text-sm truncate flex-1';
  statusCell.textContent = entity.status || '';
  inner.appendChild(statusCell);
  const display_nameCell = document.createElement('span');
  display_nameCell.className = 'text-sm truncate flex-1 text-muted-foreground italic';
  display_nameCell.textContent = (entity.name || '') + " @ " + (entity.company || '');
  inner.appendChild(display_nameCell);
  row.appendChild(inner);
  row.addEventListener('click', () => selectContact(entity.eid));
  ld_contact_list.appendChild(row);
  rowEls.set(entity.eid, {
    el: row,
    searchText: [entity.name || '', entity.email || '', entity.company || ''].join(' ').toLowerCase(),
    cells: { name: nameCell, email: emailCell, company: companyCell, status: statusCell, display_name: display_nameCell }
  });
}

function removeRow(eid) {
  const entry = rowEls.get(eid);
  if (entry) { entry.el.remove(); rowEls.delete(eid); }
}

function rebuildList() {
  ld_contact_list.innerHTML = '';
  rowEls.clear();
  const sorted = contacts.all().slice().sort((a, b) => (a.name || '').localeCompare(b.name || ''));
  for (const entity of sorted) addRow(entity);
  filterRows();
}

function filterRows() {
  const term = ld_contact_search.value.toLowerCase();
  for (const [, entry] of rowEls) {
    entry.el.hidden = (term !== '' && !entry.searchText.includes(term));
  }
}


// ── Stats ────────────────────────────────────────────
let contactCount = 0;
function updateStats() {
  contactCount = contacts.all().length;
  ld_contact_stats.textContent = 'Total: ' + contactCount;
}


// ── Form ─────────────────────────────────────────────
function handleSubmit(e) {
  e.preventDefault();
  const form_add_contact_name_val = form_add_contact_name.value.trim();
  const form_add_contact_email_val = form_add_contact_email.value.trim();
  const form_add_contact_company_val = form_add_contact_company.value.trim();
  const form_add_contact_status_val = form_add_contact_status.value.trim();
  if (!form_add_contact_name_val) return;
  contacts.add({ name: form_add_contact_name_val, email: form_add_contact_email_val, company: form_add_contact_company_val, status: form_add_contact_status_val || "active" });
  form_add_contact_name.value = '';
  form_add_contact_email.value = '';
  form_add_contact_company.value = '';
  form_add_contact_status.selectedIndex = 0;
}


// ── Persistence ──────────────────────────────────────
function saveDb() {
  try {
    localStorage.setItem("wake-crm-v2", JSON.stringify({
      contacts: contacts.snapshot(),
      notes: notes.snapshot()
    }));
  } catch(_) {}
}
function restoreDb() {
  try {
    const raw = localStorage.getItem("wake-crm-v2");
    if (!raw) return;
    const data = JSON.parse(raw);
    if (Array.isArray(data)) {
      contacts.load(data);
    } else {
      if (data.contacts) contacts.load(data.contacts);
      if (data.notes) notes.load(data.notes);
    }
  } catch(_) {}
}


// ── Compiled update paths ────────────────────────────
const updateAttr = {
  name(eid, value) {
    const rowEntry = rowEls.get(eid);
    const entity = contacts.get(eid);
    if (rowEntry) {
      rowEntry.cells.name.textContent = value;
      rowEntry.searchText = [entity.name || '', entity.email || '', entity.company || ''].join(' ').toLowerCase();
      rowEntry.cells.display_name.textContent = value + " @ " + (entity.company || '');
    }
    if (selectedContact === eid) {
      detailNodes.field_name.textContent = value;
      detailNodes.title.textContent = value;
      detailNodes.notesHeader.textContent = 'Notes for ' + value;
      if (detailNodes.field_display_name) detailNodes.field_display_name.textContent = value + " @ " + (entity.company || '');
    }
    filterRows();
    saveDb();
  },
  email(eid, value) {
    const rowEntry = rowEls.get(eid);
    const entity = contacts.get(eid);
    if (rowEntry) {
      rowEntry.cells.email.textContent = value;
      rowEntry.searchText = [entity.name || '', entity.email || '', entity.company || ''].join(' ').toLowerCase();
    }
    if (selectedContact === eid) {
      detailNodes.field_email.textContent = value;
      detailNodes.subtitle.textContent = value;
    }
    filterRows();
    saveDb();
  },
  company(eid, value) {
    const rowEntry = rowEls.get(eid);
    const entity = contacts.get(eid);
    if (rowEntry) {
      rowEntry.cells.company.textContent = value;
      rowEntry.searchText = [entity.name || '', entity.email || '', entity.company || ''].join(' ').toLowerCase();
      rowEntry.cells.display_name.textContent = (entity.name || '') + " @ " + value;
    }
    if (selectedContact === eid) {
      detailNodes.field_company.textContent = value;

      if (detailNodes.field_display_name) detailNodes.field_display_name.textContent = (entity.name || '') + " @ " + value;
    }
    filterRows();
    saveDb();
  },
  status(eid, value) {
    const rowEntry = rowEls.get(eid);
    if (rowEntry) {
      rowEntry.cells.status.textContent = value;
    }
    if (selectedContact === eid) {
      detailNodes.field_status.textContent = value;
    }
    saveDb();
  }
};


// ── Undo / Redo ─────────────────────────────────────
const undoStack = [];
const redoStack = [];
let undoing = false;
let txBuffer = null;

function recordUndo(entry) {
  if (undoing) return;
  if (txBuffer) { txBuffer.push(entry); return; }
  undoStack.push(entry);
  redoStack.length = 0;
}

function beginTransaction() { txBuffer = []; }
function commitTransaction() {
  if (txBuffer && txBuffer.length > 0) {
    undoStack.push({ type: 'batch', ops: txBuffer });
    redoStack.length = 0;
  }
  txBuffer = null;
}

function applyUndo(op) {
  if (op.type === 'update') op.store.update(op.eid, op.attr, op.old);
  if (op.type === 'add') op.store.remove(op.eid);
  if (op.type === 'remove') op.store.addBack(op.entity);
}
function applyRedo(op) {
  if (op.type === 'update') op.store.update(op.eid, op.attr, op['new']);
  if (op.type === 'add') op.store.addBack(op.entity);
  if (op.type === 'remove') op.store.remove(op.eid);
}

function undo() {
  const entry = undoStack.pop();
  if (!entry) return;
  redoStack.push(entry);
  undoing = true;
  if (entry.type === 'batch') {
    for (let i = entry.ops.length - 1; i >= 0; i--) applyUndo(entry.ops[i]);
  } else {
    applyUndo(entry);
  }
  undoing = false;
}

function redo() {
  const entry = redoStack.pop();
  if (!entry) return;
  undoStack.push(entry);
  undoing = true;
  if (entry.type === 'batch') {
    for (const op of entry.ops) applyRedo(op);
  } else {
    applyRedo(entry);
  }
  undoing = false;
}

// ── Init ─────────────────────────────────────────────
function init() {
  const root = document.getElementById('app');

  const el_1 = document.createElement("div");
  el_1.className = "flex flex-col h-screen";
  const el_2 = document.createElement("form");
  el_2.id = "form-add-contact";
  el_2.className = "flex flex-col gap-3 p-4";
  const el_3 = document.createElement("div");
  el_3.className = "flex flex-col gap-1";
  const el_4 = document.createElement("label");
  el_4.htmlFor = "form-add-contact-name";
  el_4.className = "text-xs font-medium uppercase text-muted-foreground";
  el_4.textContent = "Name";
  el_3.appendChild(el_4);
  const el_5 = document.createElement("input");
  el_5.required = true;
  el_5.placeholder = "Name";
  el_5.id = "form-add-contact-name";
  el_5.className = "px-3 py-2 border border-input rounded-md bg-background text-foreground text-sm";
  el_5.name = "form-add-contact-name";
  el_3.appendChild(el_5);
  el_2.appendChild(el_3);
  const el_6 = document.createElement("div");
  el_6.className = "flex flex-col gap-1";
  const el_7 = document.createElement("label");
  el_7.htmlFor = "form-add-contact-email";
  el_7.className = "text-xs font-medium uppercase text-muted-foreground";
  el_7.textContent = "Email";
  el_6.appendChild(el_7);
  const el_8 = document.createElement("input");
  el_8.required = true;
  el_8.placeholder = "Email";
  el_8.id = "form-add-contact-email";
  el_8.className = "px-3 py-2 border border-input rounded-md bg-background text-foreground text-sm";
  el_8.name = "form-add-contact-email";
  el_6.appendChild(el_8);
  el_2.appendChild(el_6);
  const el_9 = document.createElement("div");
  el_9.className = "flex flex-col gap-1";
  const el_10 = document.createElement("label");
  el_10.htmlFor = "form-add-contact-company";
  el_10.className = "text-xs font-medium uppercase text-muted-foreground";
  el_10.textContent = "Company";
  el_9.appendChild(el_10);
  const el_11 = document.createElement("input");
  el_11.placeholder = "Company";
  el_11.id = "form-add-contact-company";
  el_11.className = "px-3 py-2 border border-input rounded-md bg-background text-foreground text-sm";
  el_11.name = "form-add-contact-company";
  el_9.appendChild(el_11);
  el_2.appendChild(el_9);
  const el_12 = document.createElement("div");
  el_12.className = "flex flex-col gap-1";
  const el_13 = document.createElement("label");
  el_13.htmlFor = "form-add-contact-status";
  el_13.className = "text-xs font-medium uppercase text-muted-foreground";
  el_13.textContent = "Status";
  el_12.appendChild(el_13);
  const el_14 = document.createElement("select");
  el_14.id = "form-add-contact-status";
  el_14.className = "px-3 py-2 border border-input rounded-md bg-background text-foreground text-sm";
  el_14.name = "form-add-contact-status";
  { const _ph = document.createElement('option'); _ph.value = ''; _ph.textContent = "Select Status"; el_14.appendChild(_ph); }
  { const _o = document.createElement('option'); _o.value = "active"; _o.textContent = "Active"; el_14.appendChild(_o); }
  { const _o = document.createElement('option'); _o.value = "inactive"; _o.textContent = "Inactive"; el_14.appendChild(_o); }
  { const _o = document.createElement('option'); _o.value = "archived"; _o.textContent = "Archived"; el_14.appendChild(_o); }
  el_12.appendChild(el_14);
  el_2.appendChild(el_12);
  const el_15 = document.createElement("button");
  el_15.className = "px-4 py-2 bg-primary text-primary-foreground rounded-md text-sm font-medium hover:opacity-90";
  el_15.type = "submit";
  el_15.textContent = "Add Contact";
  el_2.appendChild(el_15);
  el_1.appendChild(el_2);
  const el_16 = document.createElement("div");
  el_16.className = "flex flex-1 min-h-0";
  const el_17 = document.createElement("div");
  el_17.className = "flex flex-col w-1/2 border-r border-border";
  const el_18 = document.createElement("div");
  el_18.className = "p-4 border-b border-border";
  const el_19 = document.createElement("h1");
  el_19.className = "text-lg font-semibold text-foreground mb-3";
  el_19.textContent = "Contacts";
  el_18.appendChild(el_19);
  const el_20 = document.createElement("input");
  el_20.placeholder = "Search...";
  el_20.id = "ld-contact-search";
  el_20.className = "w-full px-3 py-2 border border-border rounded-md bg-background text-foreground text-sm placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring";
  el_20.type = "text";
  el_18.appendChild(el_20);
  const el_21 = document.createElement("div");
  el_21.id = "ld-contact-stats";
  el_21.className = "mt-2 text-xs text-muted-foreground";
  el_21.textContent = "";
  el_18.appendChild(el_21);
  el_17.appendChild(el_18);
  const el_22 = document.createElement("div");
  el_22.id = "ld-contact-list";
  el_22.className = "flex-1 overflow-y-auto";
  el_17.appendChild(el_22);
  el_16.appendChild(el_17);
  const el_23 = document.createElement("div");
  el_23.id = "ld-contact-detail";
  el_23.className = "w-1/2 overflow-y-auto";
  el_16.appendChild(el_23);
  el_1.appendChild(el_16);
  root.appendChild(el_1);


  form_add_contact = el_2;
  form_add_contact_name = el_5;
  form_add_contact_email = el_8;
  form_add_contact_company = el_11;
  form_add_contact_status = el_14;
  ld_contact_search = el_20;
  ld_contact_stats = el_21;
  ld_contact_list = el_22;
  ld_contact_detail = el_23;

  buildDetailPanel();

  form_add_contact.addEventListener('submit', handleSubmit);
  ld_contact_search.addEventListener('input', filterRows);

  contacts.watch((evt) => {
    if (evt.type === 'add') {
      addRow(evt.entity);
      filterRows();
      contactCount++;
      updateStats();
      recordUndo({ type: 'add', store: contacts, eid: evt.eid, entity: evt.entity });
      saveDb();
    }
    if (evt.type === 'load') {
      rebuildList();
      contactCount = contacts.all().length;
      updateStats();
      renderDetail();
    }
    if (evt.type === 'update') {
      const fn = updateAttr[evt.attr];
      if (fn) fn(evt.eid, evt.new || '');
      recordUndo({ type: 'update', store: contacts, eid: evt.eid, attr: evt.attr, old: evt.old, 'new': evt.new });
    }
    if (evt.type === 'remove') {
      removeRow(evt.eid);
      contactCount--;
      updateStats();
      recordUndo({ type: 'remove', store: contacts, eid: evt.eid, entity: evt.entity });
      if (selectedContact === evt.eid) selectContact(null);
      saveDb();
    }
  });

  notes.watch((evt) => {
    if (evt.type === 'add' || evt.type === 'load' || evt.type === 'remove') renderNotes();
    if (evt.type === 'add') {
      recordUndo({ type: 'add', store: notes, eid: evt.eid, entity: evt.entity });
      saveDb();
    }
    if (evt.type === 'remove') {
      recordUndo({ type: 'remove', store: notes, eid: evt.eid, entity: evt.entity });
      saveDb();
    }
  });

  document.addEventListener('keydown', (e) => {
    if ((e.ctrlKey || e.metaKey) && e.key === 'z' && !e.shiftKey) { e.preventDefault(); undo(); }
    if ((e.ctrlKey || e.metaKey) && e.key === 'z' && e.shiftKey) { e.preventDefault(); redo(); }
  });

  restoreDb();
  updateStats();
  renderDetail();
}

init();
})();
