{
  description = "eddy-app — generated by eddy";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
  };

  outputs = { self, nixpkgs }:
    let
      system = "x86_64-linux";
      pkgs = import nixpkgs { inherit system; };
    in {
      packages.${system}.default = pkgs.stdenv.mkDerivation {
        pname = "eddy-app";
        version = "0.1.0";
        src = ./.;
        nativeBuildInputs = [ pkgs.nodejs_22 ];
        installPhase = ''
          mkdir -p $out/share/eddy-app $out/bin
          cp -r . $out/share/eddy-app/

          cat > $out/bin/eddy-app-server <<'SCRIPT'
          #!/usr/bin/env bash
          exec ${pkgs.nodejs_22}/bin/node $out/share/eddy-app/server.js "$@"
          SCRIPT
          chmod +x $out/bin/eddy-app-server

          cat > $out/bin/eddy-app-migrate <<'SCRIPT'
          #!/usr/bin/env bash
          echo 'SQLite: schema applied on server start'
          SCRIPT
          chmod +x $out/bin/eddy-app-migrate
        '';
      };

      nixosModules.default = { config, lib, pkgs, ... }:
        let
          cfg = config.services.eddy_app;
        in {
          options.services.eddy_app = {
            enable = lib.mkEnableOption "eddy-app server";
            port = lib.mkOption {
              type = lib.types.port;
              default = 3000;
              description = "Port for the eddy-app server";
            };
            domain = lib.mkOption {
              type = lib.types.str;
              default = "localhost";
              description = "Domain for nginx vhost";
            };
          };

          config = lib.mkIf cfg.enable {
            systemd.services.eddy_app = {
              description = "eddy-app server";
              wantedBy = [ "multi-user.target" ];
              after = [ "network.target" ];
              environment = {
                PORT = toString cfg.port;
              };
              serviceConfig = {
                ExecStart = "${self.packages.${system}.default}/bin/eddy-app-server";
                DynamicUser = true;
                StateDirectory = "eddy_app";
                WorkingDirectory = "${self.packages.${system}.default}/share/eddy-app";
                Restart = "on-failure";
                RestartSec = 5;
              };
            };

            services.nginx = {
              enable = true;
              virtualHosts.${cfg.domain} = {
                locations."/" = {
                  proxyPass = "http://127.0.0.1:${toString cfg.port}";
                  proxyWebsockets = true;
                };
              };
            };

            networking.firewall.allowedTCPPorts = [ 80 443 ];
          };
        };

      devShells.${system}.default = pkgs.mkShell {
        packages = with pkgs; [ nodejs_22 ];
      };
    };
}
