-- Generated by eddy — semantic application compiler
-- Source: eddy.app
-- This file is a build artifact. Edit the .eddy source, not this file.

CREATE TABLE contact (
  eid INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  company TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'archived'))
);

CREATE TABLE note (
  eid INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  content TEXT NOT NULL,
  contact INTEGER NOT NULL REFERENCES contact(eid) ON DELETE CASCADE,
  "created-at" TEXT NOT NULL
);

CREATE INDEX idx_note_contact ON note(contact);
