// Generated by eddy — semantic application compiler
// Source: eddy.app  |  Database: eddy-crm-v2
// This file is a build artifact. Edit the .eddy source, not this file.

import Database from 'better-sqlite3';
import { createServer } from 'node:http';
import { readFileSync, existsSync } from 'node:fs';
import { join, extname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const PORT = process.env.PORT || 3000;

// ── Database ──────────────────────────────────────
const db = new Database(join(__dirname, 'app.db'));
db.pragma('journal_mode = WAL');
db.pragma('foreign_keys = ON');

db.exec(`
  CREATE TABLE IF NOT EXISTS contact (
    eid INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    company TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'archived'))
  );
  CREATE TABLE IF NOT EXISTS note (
    eid INTEGER PRIMARY KEY AUTOINCREMENT,
    content TEXT NOT NULL,
    contact INTEGER NOT NULL REFERENCES contact(eid) ON DELETE CASCADE,
    "created-at" TEXT NOT NULL
  );
  CREATE INDEX IF NOT EXISTS idx_note_contact ON note(contact);
`);

// ── DB adapter ───────────────────────────────────
function _sqliteSql(sql) { return sql.replace(/\$\d+/g, '?'); }
const DB = {
  all: (sql, params = []) => db.prepare(_sqliteSql(sql)).all(...params),
  get: (sql, params = []) => db.prepare(_sqliteSql(sql)).get(...params),
  run: (sql, params = []) => db.prepare(_sqliteSql(sql)).run(...params),
  insert: (sql, params = []) => {
    const r = db.prepare(_sqliteSql(sql)).run(...params);
    return Number(r.lastInsertRowid);
  },
  insertWithEid: (table, sql, params) => db.prepare(_sqliteSql(sql)).run(...params),
  q: (k) => k.includes('-') ? `[${k}]` : k,
};

// ── State machines ────────────────────────────────
const TRANSITIONS = {
  'contact': {
    'active': ['inactive', 'archived'],
    'inactive': ['active', 'archived'],
    'archived': ['active']
  }
};

// ── Field whitelist ───────────────────────────────
const FIELDS = {
  'contact': ['name', 'email', 'company', 'status'],
  'note': ['content', 'contact', 'created-at']
};

// ── Helpers ───────────────────────────────────────
function json(res, data, status = 200) {
  res.writeHead(status, { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' });
  res.end(JSON.stringify(data));
}
function notFound(res) { json(res, { error: 'not found' }, 404); }
function parseBody(req) {
  return new Promise((resolve) => {
    let body = '';
    let size = 0;
    req.on('data', c => { size += c.length; if (size > 1e6) { req.destroy(); return resolve({}); } body += c; });
    req.on('end', () => { try { resolve(JSON.parse(body)); } catch { resolve({}); } });
  });
}

const MIME = { '.html': 'text/html', '.js': 'application/javascript', '.css': 'text/css', '.json': 'application/json' };

// ── Rate limiter ──────────────────────────────────
const _rates = {};
function rateOk(ip) {
  const now = Date.now();
  if (!_rates[ip]) _rates[ip] = [];
  _rates[ip] = _rates[ip].filter(t => now - t < 60000);
  if (_rates[ip].length >= 1000) return false;
  _rates[ip].push(now);
  return true;
}
setInterval(() => { const now = Date.now(); for (const ip in _rates) { _rates[ip] = _rates[ip].filter(t => now - t < 60000); if (_rates[ip].length === 0) delete _rates[ip]; } }, 60000).unref();

// ── Server ─────────────────────────────────────────
const server = createServer(async (req, res) => {
  try {
  const ip = req.socket.remoteAddress;
  if (!rateOk(ip)) return json(res, { error: 'rate limit exceeded' }, 429);
  const method = req.method;
  const path = req.url.split('?')[0];
  const start = Date.now();
  res.on('finish', () => console.log(`${method} ${path} ${res.statusCode} ${Date.now() - start}ms`));

  if (method === 'OPTIONS') {
    res.writeHead(204, { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET,POST,PUT,DELETE', 'Access-Control-Allow-Headers': 'Content-Type' });
    return res.end();
  }

  if (method === 'GET' && path === '/health') {
    return json(res, { status: 'ok', uptime: process.uptime() });
  }
  // API routes
  if (method === 'GET' && path === '/api/contacts') {
    const rows = await DB.all('SELECT * FROM contact');
    return json(res, rows);
  }
  if (method === 'GET' && path.startsWith('/api/contacts/')) {
    const eid = parseInt(path.split('/')[3]);
    const row = await DB.get('SELECT * FROM contact WHERE eid = $1', [eid]);
    if (!row) return notFound(res);
    return json(res, row);
  }
  if (method === 'POST' && path === '/api/contacts') {
    const body = await parseBody(req);
    delete body.eid;
    if (!body.status) body.status = 'active';
    const eid = await DB.insert('INSERT INTO contact (name, email, company, status) VALUES ($1, $2, $3, $4)', [body['name'], body['email'], body['company'], body['status']]);
    return json(res, { eid, ...body }, 201);
  }
  if (method === 'PUT' && path.startsWith('/api/contacts/')) {
    const eid = parseInt(path.split('/')[3]);
    const body = await parseBody(req);
    const existing = await DB.get('SELECT * FROM contact WHERE eid = $1', [eid]);
    if (!existing) return notFound(res);
    if (body.status && body.status !== existing.status) {
      const allowed = TRANSITIONS['contact'][existing.status];
      if (!allowed || !allowed.includes(body.status)) {
        return json(res, { error: 'Invalid transition: ' + existing.status + ' → ' + body.status }, 400);
      }
    }
    const allowed = FIELDS['contact'];
    const keys = Object.keys(body).filter(k => allowed.includes(k));
    if (keys.length === 0) return json(res, { error: 'no valid fields' }, 400);
    const sets = keys.map((k, i) => `${DB.q(k)} = $${i+1}`).join(', ');
    const vals = keys.map(k => body[k]);
    await DB.run(`UPDATE contact SET ${sets} WHERE eid = $${keys.length + 1}`, [...vals, eid]);
    return json(res, { eid, ...existing, ...body });
  }
  if (method === 'DELETE' && path.startsWith('/api/contacts/')) {
    const eid = parseInt(path.split('/')[3]);
    await DB.run('DELETE FROM note WHERE contact = $1', [eid]);
    await DB.run('DELETE FROM contact WHERE eid = $1', [eid]);
    return json(res, { ok: true });
  }

  if (method === 'GET' && path === '/api/notes') {
    const rows = await DB.all('SELECT * FROM note');
    return json(res, rows);
  }
  if (method === 'GET' && path.startsWith('/api/notes/')) {
    const eid = parseInt(path.split('/')[3]);
    const row = await DB.get('SELECT * FROM note WHERE eid = $1', [eid]);
    if (!row) return notFound(res);
    return json(res, row);
  }
  if (method === 'POST' && path === '/api/notes') {
    const body = await parseBody(req);
    delete body.eid;
    const eid = await DB.insert('INSERT INTO note (content, contact, "created-at") VALUES ($1, $2, $3)', [body['content'], body['contact'], body['created-at']]);
    return json(res, { eid, ...body }, 201);
  }
  if (method === 'PUT' && path.startsWith('/api/notes/')) {
    const eid = parseInt(path.split('/')[3]);
    const body = await parseBody(req);
    const existing = await DB.get('SELECT * FROM note WHERE eid = $1', [eid]);
    if (!existing) return notFound(res);
    const allowed = FIELDS['note'];
    const keys = Object.keys(body).filter(k => allowed.includes(k));
    if (keys.length === 0) return json(res, { error: 'no valid fields' }, 400);
    const sets = keys.map((k, i) => `${DB.q(k)} = $${i+1}`).join(', ');
    const vals = keys.map(k => body[k]);
    await DB.run(`UPDATE note SET ${sets} WHERE eid = $${keys.length + 1}`, [...vals, eid]);
    return json(res, { eid, ...existing, ...body });
  }
  if (method === 'DELETE' && path.startsWith('/api/notes/')) {
    const eid = parseInt(path.split('/')[3]);
    await DB.run('DELETE FROM note WHERE eid = $1', [eid]);
    return json(res, { ok: true });
  }

  // API index
  if (method === 'GET' && path === '/api') {
    return json(res, { entities: ['contacts', 'notes'] });
  }

  // Static files
  const file = path === '/' ? '/index.html' : path;
  const filePath = join(__dirname, file);
  if (!filePath.startsWith(__dirname)) return notFound(res);
  if (existsSync(filePath)) {
    const ext = extname(filePath);
    res.writeHead(200, { 'Content-Type': MIME[ext] || 'text/plain' });
    return res.end(readFileSync(filePath));
  }

  notFound(res);
  } catch (err) {
    console.error(`ERROR ${req.method} ${req.url}:`, err.message);
    if (!res.headersSent) json(res, { error: 'internal server error' }, 500);
  }
});

server.listen(PORT, () => {
  console.log(`eddy server (${'eddy.app'}) → http://localhost:${PORT}`);
  console.log(`  API: /api  |  entities: contacts, notes  |  db: eddy-crm-v2`);
});

function shutdown() {
  console.log('shutting down...');
  server.close(() => { db.close(); process.exit(0); });
  setTimeout(() => process.exit(1), 5000);
}
process.on('SIGTERM', shutdown);
process.on('SIGINT', shutdown);
