// Generated by wake — semantic application compiler
// Source: wake.app
// Integration tests derived from entity graph

import { describe, it, before, after } from 'node:test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { unlinkSync, existsSync } from 'node:fs';

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const PORT = 19000 + Math.floor(Math.random() * 1000);
const DB_PATH = join(__dirname, 'app.db');
let _uid = 0;
function uid(p) { return p + '_' + (++_uid); }

async function api(method, path, body) {
  const opts = { method, headers: { 'Content-Type': 'application/json' } };
  if (body) opts.body = JSON.stringify(body);
  const res = await fetch(`http://localhost:${PORT}${path}`, opts);
  const data = await res.json().catch(() => null);
  return { status: res.status, data };
}

let serverProc;

before(async () => {
  if (existsSync(DB_PATH)) unlinkSync(DB_PATH);
  serverProc = spawn('node', [join(__dirname, 'server.js')], {
    env: { ...process.env, PORT: String(PORT) },
    stdio: ['pipe', 'pipe', 'pipe']
  });
  await new Promise((resolve, reject) => {
    const timeout = setTimeout(() => reject(new Error('Server start timeout')), 5000);
    serverProc.stdout.on('data', (d) => {
      if (d.toString().includes('wake server')) { clearTimeout(timeout); resolve(); }
    });
  });
});

after(() => {
  serverProc.kill();
  if (existsSync(DB_PATH)) unlinkSync(DB_PATH);
});

function buildContact(o = {}) { return { 'name': uid('name'), 'email': uid('email'), 'company': uid('company'), ...o }; }
function buildNote(o = {}) { return { 'content': uid('content'), 'created-at': uid('created-at'), ...o }; }
async function createContact(overrides = {}) {
  const o = buildContact(overrides);
  const { data } = await api('POST', '/api/contacts', o);
  return data;
}
async function createNote(overrides = {}) {
  const o = buildNote(overrides);
  if (!o['contact']) { const p = await createContact(); o['contact'] = Number(p.eid); }
  const { data } = await api('POST', '/api/notes', o);
  return data;
}

describe('health', () => {
  it('GET /health returns ok', async () => {
    const { status, data } = await api('GET', '/health');
    assert.equal(status, 200);
    assert.equal(data.status, 'ok');
    assert.ok(typeof data.uptime === 'number');
  });
});describe('contact CRUD', () => {
  it('creates via POST', async () => {
    const e = await createContact();
    assert.ok(e.eid);
  });

  it('lists via GET', async () => {
    await createContact();
    const { status, data } = await api('GET', '/api/contacts');
    assert.equal(status, 200);
    assert.ok(Array.isArray(data));
  });

  it('gets by id', async () => {
    const e = await createContact();
    const { status, data } = await api('GET', `/api/contacts/${e.eid}`);
    assert.equal(status, 200);
    assert.equal(Number(data.eid), Number(e.eid));
  });

  it('updates via PUT', async () => {
    const e = await createContact();
    const { status, data } = await api('PUT', `/api/contacts/${e.eid}`, { 'name': 'updated' });
    assert.equal(status, 200);
    assert.equal(data['name'], 'updated');
  });

  it('returns 404 for missing', async () => {
    const { status } = await api('GET', '/api/contacts/99999');
    assert.equal(status, 404);
  });

  it('deletes and verifies gone', async () => {
    const e = await createContact();
    const { status } = await api('DELETE', `/api/contacts/${e.eid}`);
    assert.equal(status, 200);
    const { status: s2 } = await api('GET', `/api/contacts/${e.eid}`);
    assert.equal(s2, 404);
  });
});

describe('note CRUD', () => {
  it('creates via POST', async () => {
    const e = await createNote();
    assert.ok(e.eid);
  });

  it('lists via GET', async () => {
    await createNote();
    const { status, data } = await api('GET', '/api/notes');
    assert.equal(status, 200);
    assert.ok(Array.isArray(data));
  });

  it('gets by id', async () => {
    const e = await createNote();
    const { status, data } = await api('GET', `/api/notes/${e.eid}`);
    assert.equal(status, 200);
    assert.equal(Number(data.eid), Number(e.eid));
  });

  it('updates via PUT', async () => {
    const e = await createNote();
    const { status, data } = await api('PUT', `/api/notes/${e.eid}`, { 'content': 'updated' });
    assert.equal(status, 200);
    assert.equal(data['content'], 'updated');
  });

  it('returns 404 for missing', async () => {
    const { status } = await api('GET', '/api/notes/99999');
    assert.equal(status, 404);
  });

  it('deletes and verifies gone', async () => {
    const e = await createNote();
    const { status } = await api('DELETE', `/api/notes/${e.eid}`);
    assert.equal(status, 200);
    const { status: s2 } = await api('GET', `/api/notes/${e.eid}`);
    assert.equal(s2, 404);
  });
});

describe('contact constraints', () => {
  it('rejects duplicate email', async () => {
    const dup = uid('dup');
    await createContact({ 'email': dup });
    const { status } = await api('POST', '/api/contacts', buildContact({ 'email': dup }));
    assert.ok(status >= 400);
  });

  it('survives SQL injection in name', async () => {
    const e = await createContact({ 'name': "'; DROP TABLE contact; --" });
    assert.ok(e.eid);
    const { data } = await api('GET', '/api/contacts');
    assert.ok(Array.isArray(data));
  });

  it('rejects bogus status value', async () => {
    const e = await createContact();
    const { status } = await api('PUT', `/api/contacts/${e.eid}`, { status: 'NONEXISTENT' });
    assert.equal(status, 400);
  });

  it('ignores unknown fields in PUT', async () => {
    const e = await createContact();
    const { status, data } = await api('PUT', `/api/contacts/${e.eid}`, { __hack__: 'x' });
    assert.equal(status, 400);
  });

});

describe('note constraints', () => {
  it('survives SQL injection in content', async () => {
    const e = await createNote({ 'content': "'; DROP TABLE note; --" });
    assert.ok(e.eid);
    const { data } = await api('GET', '/api/notes');
    assert.ok(Array.isArray(data));
  });

  it('rejects invalid contact ref', async () => {
    const { status } = await api('POST', '/api/notes', buildNote({ 'contact': 99999 }));
    assert.ok(status >= 400);
  });

  it('ignores unknown fields in PUT', async () => {
    const e = await createNote();
    const { status, data } = await api('PUT', `/api/notes/${e.eid}`, { __hack__: 'x' });
    assert.equal(status, 400);
  });

});

describe('ContactStatus transitions', () => {
  it('defaults to active', async () => {
    const e = await createContact();
    assert.equal(e.status, 'active');
  });

  it('active → inactive succeeds', async () => {
    const created = await createContact();
    const { status } = await api('PUT', `/api/contacts/${created.eid}`, { status: 'inactive' });
    assert.equal(status, 200);
  });

  it('active → archived succeeds', async () => {
    const created = await createContact();
    const { status } = await api('PUT', `/api/contacts/${created.eid}`, { status: 'archived' });
    assert.equal(status, 200);
  });

  it('inactive → active succeeds', async () => {
    const created = await createContact();
    await api('PUT', `/api/contacts/${created.eid}`, { status: 'inactive' });
    const { status } = await api('PUT', `/api/contacts/${created.eid}`, { status: 'active' });
    assert.equal(status, 200);
  });

  it('inactive → archived succeeds', async () => {
    const created = await createContact();
    await api('PUT', `/api/contacts/${created.eid}`, { status: 'inactive' });
    const { status } = await api('PUT', `/api/contacts/${created.eid}`, { status: 'archived' });
    assert.equal(status, 200);
  });

  it('archived → active succeeds', async () => {
    const created = await createContact();
    await api('PUT', `/api/contacts/${created.eid}`, { status: 'archived' });
    const { status } = await api('PUT', `/api/contacts/${created.eid}`, { status: 'active' });
    assert.equal(status, 200);
  });

  it('archived → inactive rejects', async () => {
    const created = await createContact();
    await api('PUT', `/api/contacts/${created.eid}`, { status: 'archived' });
    const { status } = await api('PUT', `/api/contacts/${created.eid}`, { status: 'inactive' });
    assert.equal(status, 400);
  });

});

describe('cascade: note → contact', () => {
  it('deleting contact removes its notes', async () => {
    const parent = await createContact();
    await createNote({ 'contact': Number(parent.eid) });
    await api('DELETE', `/api/contacts/${parent.eid}`);
    const { data } = await api('GET', '/api/notes');
    const orphaned = data.filter(r => r['contact'] === Number(parent.eid));
    assert.equal(orphaned.length, 0);
  });
});

