// Generated by eddy — semantic UI compiler
// Source: eddy.tracker
// This file is a build artifact. Edit the .eddy source, not this file.

(function() {
'use strict';

// ── Stores ────────────────────────────────────────
const tasks = (() => {
  let nextEid = 1;
  const entities = new Map();
  const watchers = [];
  function notify(evt) { for (const fn of watchers) fn(evt); }
  return {
    add(fields) {
      const eid = nextEid++;
      const entity = { ...fields, eid };
      entities.set(eid, entity);
      notify({ type: 'add', eid, entity });
      return entity;
    },
    get(eid) { return entities.get(eid); },
    update(eid, attr, value) {
      const entity = entities.get(eid);
      if (!entity) return;
      const old = entity[attr];
      entity[attr] = value;
      notify({ type: 'update', eid, entity, attr, old, 'new': value });
    },
    all() { return Array.from(entities.values()); },
    remove(eid) {
      const entity = entities.get(eid);
      if (!entity) return;
      entities.delete(eid);
      notify({ type: 'remove', eid, entity });
    },
    addBack(entity) {
      entities.set(entity.eid, entity);
      if (entity.eid >= nextEid) nextEid = entity.eid + 1;
      notify({ type: 'add', eid: entity.eid, entity });
    },
    watch(fn) { watchers.push(fn); },
    load(items) {
      entities.clear();
      let maxEid = 0;
      for (const item of items) { entities.set(item.eid, item); if (item.eid > maxEid) maxEid = item.eid; }
      nextEid = maxEid + 1;
      notify({ type: 'load' });
    },
    snapshot() { return Array.from(entities.values()); }
  };
})();

// ── Components ──────────────────────────────────────
function task_row_create(props) {
  const el_0 = document.createElement("div");
  el_0.className = "flex items-center gap-4 px-4 py-2.5 border-b border-border";
  const el_1 = document.createElement("span");
  el_1.className = "flex-1 text-sm";
  el_1.textContent = props.title || '';
  el_0.appendChild(el_1);
  const whenAnchor_2 = document.createComment('when:done');
  el_0.appendChild(whenAnchor_2);
  let when_2 = [];
  function when_2_update(condition) {
    if (condition && when_2.length === 0) {
  const el_3 = document.createElement("span");
  el_3.className = "ml-1 text-xs text-green-600 font-medium";
  el_3.textContent = "Done";
      el_0.insertBefore(el_3, whenAnchor_2);
      when_2 = [el_3];
    } else if (!condition && when_2.length > 0) {
      for (const el of when_2) el.remove();
      when_2 = [];
    }
  }
  when_2_update(props.done);
  return {
    el: el_0,
    update: {
    title(v) { el_1.textContent = v; },
    done(v) { when_2_update(v); }
    },
    destroy() { el_0.remove(); }
  };
}

function task_detail_create(props) {
  const el_0 = document.createElement("div");
  el_0.className = "p-6";
  const el_1 = document.createElement("h2");
  el_1.className = "text-lg font-semibold mb-2";
  el_1.textContent = props.title || '';
  el_0.appendChild(el_1);
  const whenAnchor_2 = document.createComment('when:done');
  el_0.appendChild(whenAnchor_2);
  let when_2 = [];
  function when_2_update(condition) {
    if (condition && when_2.length === 0) {
  const el_3 = document.createElement("div");
  el_3.className = "mt-2 px-3 py-1.5 bg-green-50 border border-green-200 rounded text-sm text-green-700";
  const el_4 = document.createElement("span");
  el_4.textContent = "Completed";
  el_3.appendChild(el_4);
      el_0.insertBefore(el_3, whenAnchor_2);
      when_2 = [el_3];
    } else if (!condition && when_2.length > 0) {
      for (const el of when_2) el.remove();
      when_2 = [];
    }
  }
  when_2_update(props.done);
  return {
    el: el_0,
    update: {
    title(v) { el_1.textContent = v; },
    done(v) { when_2_update(v); }
    },
    destroy() { el_0.remove(); }
  };
}

function task_simple_create(props) {
  const el_0 = document.createElement("div");
  el_0.className = "px-4 py-2.5 border-b border-border";
  const el_1 = document.createElement("span");
  el_1.className = "text-sm";
  el_1.textContent = props.title || '';
  el_0.appendChild(el_1);
  return {
    el: el_0,
    update: {
    title(v) { el_1.textContent = v; }
    },
    destroy() { el_0.remove(); }
  };
}

// ── Undo / Redo ─────────────────────────────────────
const undoStack = [];
const redoStack = [];
let undoing = false;
let txBuffer = null;

function recordUndo(entry) {
  if (undoing) return;
  if (txBuffer) { txBuffer.push(entry); return; }
  undoStack.push(entry);
  redoStack.length = 0;
}

function beginTransaction() { txBuffer = []; }
function commitTransaction() {
  if (txBuffer && txBuffer.length > 0) {
    undoStack.push({ type: 'batch', ops: txBuffer });
    redoStack.length = 0;
  }
  txBuffer = null;
}

function applyUndo(op) {
  if (op.type === 'update') op.store.update(op.eid, op.attr, op.old);
  if (op.type === 'add') op.store.remove(op.eid);
  if (op.type === 'remove') op.store.addBack(op.entity);
}
function applyRedo(op) {
  if (op.type === 'update') op.store.update(op.eid, op.attr, op['new']);
  if (op.type === 'add') op.store.addBack(op.entity);
  if (op.type === 'remove') op.store.remove(op.eid);
}

function undo() {
  const entry = undoStack.pop();
  if (!entry) return;
  redoStack.push(entry);
  undoing = true;
  if (entry.type === 'batch') {
    for (let i = entry.ops.length - 1; i >= 0; i--) applyUndo(entry.ops[i]);
  } else {
    applyUndo(entry);
  }
  undoing = false;
}

function redo() {
  const entry = redoStack.pop();
  if (!entry) return;
  undoStack.push(entry);
  undoing = true;
  if (entry.type === 'batch') {
    for (const op of entry.ops) applyRedo(op);
  } else {
    applyRedo(entry);
  }
  undoing = false;
}

// ── Persistence ──────────────────────────────────────
function saveDb() {
  try {
    localStorage.setItem("eddy-tracker", JSON.stringify({
      tasks: tasks.snapshot()
    }));
  } catch(_) {}
}
function restoreDb() {
  try {
    const raw = localStorage.getItem("eddy-tracker");
    if (!raw) return;
    const data = JSON.parse(raw);
    if (Array.isArray(data)) {
      tasks.load(data);
    } else {
      if (data.tasks) tasks.load(data.tasks);
    }
  } catch(_) {}
}

// ── Undo watchers ───────────────────────────────────
tasks.watch((evt) => {
  if (evt.type === 'add') {
    recordUndo({ type: 'add', store: tasks, eid: evt.eid, entity: evt.entity });
    saveDb();
  }
  if (evt.type === 'update') {
    recordUndo({ type: 'update', store: tasks, eid: evt.eid, attr: evt.attr, old: evt.old, 'new': evt.new });
    saveDb();
  }
  if (evt.type === 'remove') {
    recordUndo({ type: 'remove', store: tasks, eid: evt.eid, entity: evt.entity });
    saveDb();
  }
});

// ── Init ─────────────────────────────────────────────
function init() {
  const root = document.getElementById('app');
  const app = document.createElement('div');
  app.className = 'flex flex-col h-screen';

  const nav = document.createElement('nav');
  nav.className = 'flex gap-4 px-4 py-2 border-b border-border bg-muted/30';
  const navButtons = {};
    const nav_tasks = document.createElement('button');
    nav_tasks.textContent = "Tasks";
    nav_tasks.addEventListener('click', () => navigate("tasks"));
    nav.appendChild(nav_tasks);
    navButtons["tasks"] = nav_tasks;

    const nav_board = document.createElement('button');
    nav_board.textContent = "Board";
    nav_board.addEventListener('click', () => navigate("board"));
    nav.appendChild(nav_board);
    navButtons["board"] = nav_board;

  app.appendChild(nav);

  const viewContainers = {};

  // ── View: tasks ──
  (function() {
    const viewEl = document.createElement('div');
    viewEl.className = 'flex flex-col flex-1 min-h-0';

    const formEl = document.createElement('form');
    formEl.className = 'flex flex-col gap-3 p-4';
    const form_title_label = document.createElement('label');
    form_title_label.className = 'text-xs font-medium uppercase text-muted-foreground';
    form_title_label.textContent = "Title";
    formEl.appendChild(form_title_label);
    const form_title = document.createElement('input');
    form_title.className = 'px-3 py-2 border border-input rounded-md bg-background text-foreground text-sm';
    form_title.placeholder = "Title";
    formEl.appendChild(form_title);
    const form_done_label = document.createElement('label');
    form_done_label.className = 'text-xs font-medium uppercase text-muted-foreground';
    form_done_label.textContent = "Done";
    formEl.appendChild(form_done_label);
    const form_done = document.createElement('input');
    form_done.className = 'px-3 py-2 border border-input rounded-md bg-background text-foreground text-sm';
    form_done.placeholder = "Done";
    formEl.appendChild(form_done);
    const submitBtn = document.createElement('button');
    submitBtn.type = 'submit';
    submitBtn.className = 'px-4 py-2 bg-primary text-primary-foreground rounded-md text-sm font-medium hover:opacity-90';
    submitBtn.textContent = 'Add';
    formEl.appendChild(submitBtn);
    formEl.addEventListener('submit', (e) => {
      e.preventDefault();
      const first = form_title.value.trim();
      if (!first) return;
      tasks.add({ title: form_title.value.trim(), done: form_done.value.trim() });
      form_title.value = '';
      form_done.value = '';
    });
    viewEl.appendChild(formEl);

    const headerEl = document.createElement('div');
    headerEl.className = 'p-4 border-b border-border';
    const titleEl = document.createElement('h1');
    titleEl.className = 'text-lg font-semibold text-foreground';
    titleEl.textContent = "Tasks";
    headerEl.appendChild(titleEl);
    const statsEl = document.createElement('div');
    statsEl.className = 'mt-2 text-xs text-muted-foreground';
    headerEl.appendChild(statsEl);
    const listEl = document.createElement('div');
    listEl.className = 'flex-1 overflow-y-auto';

    const splitPane = document.createElement('div');
    splitPane.className = 'flex flex-1 min-h-0';
    const leftPane = document.createElement('div');
    leftPane.className = 'flex flex-col w-1/2 border-r border-border';
    leftPane.appendChild(headerEl);
    leftPane.appendChild(listEl);
    splitPane.appendChild(leftPane);
    const rightPane = document.createElement('div');
    rightPane.className = 'w-1/2 overflow-y-auto';
    const detailEmpty = document.createElement('div');
    detailEmpty.className = 'flex items-center justify-center h-full text-muted-foreground text-sm';
    detailEmpty.textContent = 'Select an item to view details';
    rightPane.appendChild(detailEmpty);
    splitPane.appendChild(rightPane);
    viewEl.appendChild(splitPane);

    let selectedEid = null;
    let detailInst = null;
    function selectItem(eid) {
      selectedEid = eid;
      if (detailInst) { detailInst.destroy(); detailInst = null; }
      if (eid === null) { detailEmpty.hidden = false; return; }
      detailEmpty.hidden = true;
      const entity = tasks.get(eid);
      if (!entity) return;
      detailInst = task_detail_create(entity);
      rightPane.appendChild(detailInst.el);
    }

    const instances = new Map();
    tasks.watch((evt) => {
      if (evt.type === 'add') {
        const inst = task_row_create(evt.entity);
        inst.el.className = (inst.el.className || '') + ' cursor-pointer hover:bg-muted/50';
        inst.el.addEventListener('click', () => selectItem(evt.eid));
        listEl.appendChild(inst.el);
        instances.set(evt.eid, inst);
        statsEl.textContent = 'Total: ' + instances.size;
      }
      if (evt.type === 'update') {
        const inst = instances.get(evt.eid);
        if (inst && inst.update[evt.attr]) inst.update[evt.attr](evt.new || '');
        if (selectedEid === evt.eid && detailInst && detailInst.update[evt.attr]) detailInst.update[evt.attr](evt.new || '');
      }
      if (evt.type === 'remove') {
        const inst = instances.get(evt.eid);
        if (inst) { inst.destroy(); instances.delete(evt.eid); }
        statsEl.textContent = 'Total: ' + instances.size;
        if (selectedEid === evt.eid) selectItem(null);
      }
      if (evt.type === 'load') {
        listEl.innerHTML = '';
        instances.clear();
        if (selectedEid) selectItem(null);
        for (const entity of tasks.all()) {
          const inst = task_row_create(entity);
          inst.el.className = (inst.el.className || '') + ' cursor-pointer hover:bg-muted/50';
          inst.el.addEventListener('click', () => selectItem(entity.eid));
          listEl.appendChild(inst.el);
          instances.set(entity.eid, inst);
        }
        statsEl.textContent = 'Total: ' + instances.size;
      }
    });

    viewContainers["tasks"] = viewEl;
    app.appendChild(viewEl);
  })();

  // ── View: board ──
  (function() {
    const viewEl = document.createElement('div');
    viewEl.className = 'flex flex-col flex-1 min-h-0';

    const formEl = document.createElement('form');
    formEl.className = 'flex flex-col gap-3 p-4';
    const form_title_label = document.createElement('label');
    form_title_label.className = 'text-xs font-medium uppercase text-muted-foreground';
    form_title_label.textContent = "Title";
    formEl.appendChild(form_title_label);
    const form_title = document.createElement('input');
    form_title.className = 'px-3 py-2 border border-input rounded-md bg-background text-foreground text-sm';
    form_title.placeholder = "Title";
    formEl.appendChild(form_title);
    const submitBtn = document.createElement('button');
    submitBtn.type = 'submit';
    submitBtn.className = 'px-4 py-2 bg-primary text-primary-foreground rounded-md text-sm font-medium hover:opacity-90';
    submitBtn.textContent = 'Add';
    formEl.appendChild(submitBtn);
    formEl.addEventListener('submit', (e) => {
      e.preventDefault();
      const first = form_title.value.trim();
      if (!first) return;
      tasks.add({ title: form_title.value.trim() });
      form_title.value = '';
    });
    viewEl.appendChild(formEl);

    const headerEl = document.createElement('div');
    headerEl.className = 'p-4 border-b border-border';
    const titleEl = document.createElement('h1');
    titleEl.className = 'text-lg font-semibold text-foreground';
    titleEl.textContent = "Board";
    headerEl.appendChild(titleEl);
    const statsEl = document.createElement('div');
    statsEl.className = 'mt-2 text-xs text-muted-foreground';
    headerEl.appendChild(statsEl);
    const listEl = document.createElement('div');
    listEl.className = 'flex-1 overflow-y-auto';

    viewEl.appendChild(headerEl);
    viewEl.appendChild(listEl);

    const instances = new Map();
    tasks.watch((evt) => {
      if (evt.type === 'add') {
        const inst = task_simple_create(evt.entity);
        inst.el.className = (inst.el.className || '') + ' cursor-pointer hover:bg-muted/50';
        listEl.appendChild(inst.el);
        instances.set(evt.eid, inst);
        statsEl.textContent = 'Total: ' + instances.size;
      }
      if (evt.type === 'update') {
        const inst = instances.get(evt.eid);
        if (inst && inst.update[evt.attr]) inst.update[evt.attr](evt.new || '');
      }
      if (evt.type === 'remove') {
        const inst = instances.get(evt.eid);
        if (inst) { inst.destroy(); instances.delete(evt.eid); }
        statsEl.textContent = 'Total: ' + instances.size;
      }
      if (evt.type === 'load') {
        listEl.innerHTML = '';
        instances.clear();
        for (const entity of tasks.all()) {
          const inst = task_simple_create(entity);
          inst.el.className = (inst.el.className || '') + ' cursor-pointer hover:bg-muted/50';
          listEl.appendChild(inst.el);
          instances.set(entity.eid, inst);
        }
        statsEl.textContent = 'Total: ' + instances.size;
      }
    });

    viewContainers["board"] = viewEl;
    app.appendChild(viewEl);
  })();


  root.appendChild(app);

  let currentView = '';
  function navigate(name) {
    for (const [n, el] of Object.entries(viewContainers)) {
      el.hidden = n !== name;
    }
    currentView = name;
    location.hash = '#' + name;
    for (const [n, btn] of Object.entries(navButtons)) {
      btn.className = n === name
        ? "px-3 py-1.5 text-sm font-medium text-foreground border-b-2 border-primary"
        : "px-3 py-1.5 text-sm text-muted-foreground hover:text-foreground";
    }
  }

  const hash = location.hash.slice(1) || "tasks";
  navigate(hash);
  window.addEventListener('hashchange', () => {
    const h = location.hash.slice(1);
    if (h && viewContainers[h]) navigate(h);
  });

  document.addEventListener('keydown', (e) => {
    if ((e.ctrlKey || e.metaKey) && e.key === 'z' && !e.shiftKey) { e.preventDefault(); undo(); }
    if ((e.ctrlKey || e.metaKey) && e.key === 'z' && e.shiftKey) { e.preventDefault(); redo(); }
  });

  restoreDb();
}

init();
})();
(node:1956111) [MODULE_TYPELESS_PACKAGE_JSON] Warning: Module type of file:///home/tom/code/eddy/web/compiler/dist/reader.js is not specified and it doesn't parse as CommonJS.
Reparsing as ES module because module syntax was detected. This incurs a performance overhead.
To eliminate this warning, add "type": "module" to /home/tom/code/eddy/web/package.json.
(Use `node --trace-warnings ...` to show where the warning was created)
